### ISSUE TITLE
Crash on login with bitwarden_rs

### ISSUE THREAD

**Issue by paulens12** [bitwarden/mobile#1144]
## Describe the Bug

App crashes when trying to log in

## Steps To Reproduce

Add a self-hosted server URL and log in

## Expected Result

Successful log in

## Actual Result

On initial log in, the loading wheel spins for a while and then the app crashes.
When I open the app again, it gives me the option to "unlock" using my password - if I do that, it crashes instantly without any loading animation.
Logcat below.

## Environment

- Device: Google Pixel 3a
- Operating system: Android 10 (CalyxOS)
- Build Version 2.6.1 - can't open settings in the app because it crashes too fast
- Is this a Beta release? No

## Additional Context

Using latest build from F-Droid repo (2.6.1)

As a side note, where can I get beta builds?

## Logcat

```
11-08 22:07:17.903  6061  6087 I x8bit.bitwarde: Explicit concurrent copying GC freed 914(198KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 1355KB/1867KB, paused 22us total 5.869ms
11-08 22:07:17.976  6061  6087 I x8bit.bitwarde: Explicit concurrent copying GC freed 218(34KB) AllocSpace objects, 0(0B) LOS objects, 26% free, 1404KB/1916KB, paused 24us total 6.088ms
11-08 22:07:18.035  6061  6202 I AdrenoGLES: QUALCOMM build                   : ba734b1, I0a3e8c4129
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Build Date                       : 11/11/19
11-08 22:07:18.035  6061  6202 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Local Branch                     :
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.8.9.C1.08.00.00.516.287
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Remote Branch                    : NONE
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Reconstruct Branch               : NOTHING
11-08 22:07:18.035  6061  6202 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
11-08 22:07:18.038  6061  6202 I AdrenoGLES: PFP: 0x016ee183, ME: 0x00000000
11-08 22:07:18.141   592   592 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
11-08 22:07:18.141  6061  6202 W Gralloc3: mapper 3.x is not supported
11-08 22:07:18.154  1041  1322 I ActivityTaskManager: Displayed com.x8bit.bitwarden/.MainActivity: +988ms
11-08 22:07:18.435   830   830 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
11-08 22:07:18.440  2772  2772 W Appboy v7.0.0 .j.c.a: SDK is disabled. Not performing action on SDK.
11-08 22:07:18.538  1041  2380 D BiometricService: canAuthenticate: User=0, Caller=0
11-08 22:07:18.538  1041  2380 D BiometricService: checkAndGetBiometricModality: user=0 isHardwareDetected=true hasTemplatesEnrolled=true enabledForApps=true
11-08 22:07:18.564  1041  1041 D BiometricService: checkAndGetBiometricModality: user=0 isHardwareDetected=true hasTemplatesEnrolled=true enabledForApps=true
11-08 22:07:18.564  1041  1041 D BiometricService: Creating auth session. Modality: 1, cookie: 1453713756
11-08 22:07:18.565  1041  1041 V FingerprintService: startAuthentication(com.x8bit.bitwarden)
11-08 22:07:18.565  1041  1041 V FingerprintService: Returning cookie: 1453713756
11-08 22:07:18.566  1041  1041 D BiometricService: Matched cookie: 1453713756, 0 remaining
11-08 22:07:18.566  1041  1041 V FingerprintService: starting client AuthenticationClientImpl(com.x8bit.bitwarden) targetUserId: 0 currentUserId: 0 cookie: 1453713756/1453713756
11-08 22:07:18.566  1190  1326 I fpc_tac : fpc_irq_wait {{20,10,0},{17,1,1}}
11-08 22:07:18.567  1190  1326 E fpc_tac : fpc_irq_wait error FPC_ERROR_CANCELLED
11-08 22:07:18.590  1041  1041 W FingerprintService: client com.x8bit.bitwarden is authenticating...
11-08 22:07:18.592  1785  1785 D BiometricDialogImpl: showBiometricDialog, type: 1, requireConfirmation: false
11-08 22:07:18.603  1785  1785 D BiometricDialogImpl: handleShowDialog,  savedState: null mCurrentDialog: com.android.systemui.biometrics.FingerprintDialogView{846d1a0 V.E...... ......I. 0,0-1080,2088} newDialog: com.android.systemui.biometrics.FingerprintDialogView{d864ea7 V.E...... ......I. 0,0-0,0} type: 1
11-08 22:07:19.225  1190  1325 D fpc_hidl: onAcquired(code=0, vendor=0)
11-08 22:07:19.226  1041  1041 V FingerprintService: Acquired: 0 0
11-08 22:07:19.229  1190  1325 D fpc_hidl: onAuthenticated(fid=-736566765, gid=0)
11-08 22:07:19.229  1041  1041 V BiometricStats: Authentication latency: 3
11-08 22:07:19.230  1041  1041 V FingerprintService: onAuthenticated(true), ID:-736566765, Owner: com.x8bit.bitwarden, isBP: true, listener: com.android.server.biometrics.fingerprint.FingerprintService$BiometricPromptServiceListenerImpl@c0719b1, requireConfirmation: false, user: 0
11-08 22:07:19.234  1041  1041 V FingerprintService: Done with client: com.x8bit.bitwarden
11-08 22:07:19.235  1111  1111 D keystore: AddAuthenticationToken: timestamp = 456730, time_received = 444
11-08 22:07:19.239  1785  1785 D BiometricDialogImpl: onBiometricAuthenticated: true reason: null
11-08 22:07:19.239  1785  1785 D BiometricDialogImpl: handleBiometricAuthenticated: true
11-08 22:07:19.254  1785  1785 D BiometricDialogImpl: handleHideDialog, userCanceled: false
11-08 22:07:19.639  1785  1785 E FingerprintDialogView: Animation not found, 1 -> 0
11-08 22:07:19.849  6061  6061 I x8bit.bitwarde: Explicit concurrent copying GC freed 4636(693KB) AllocSpace objects, 3(124KB) LOS objects, 49% free, 2241KB/4482KB, paused 31us total 11.940ms
11-08 22:07:20.168  6061  6061 I x8bit.bitwarde: Explicit concurrent copying GC freed 5749(431KB) AllocSpace objects, 2(104KB) LOS objects, 49% free, 2462KB/4924KB, paused 28us total 13.014ms
11-08 22:07:20.327  6061  6061 I Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
11-08 22:07:20.340  6061  6061 I MonoDroid: UNHANDLED EXCEPTION:
11-08 22:07:20.353  6061  6061 I MonoDroid: System.NullReferenceException: Object reference not set to an instance of an object
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.Core.Models.Domain.Login..ctor (Bit.Core.Models.Data.LoginData obj, System.Boolean alreadyEncrypted) [0x00015] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.Core.Models.Domain.Cipher..ctor (Bit.Core.Models.Data.CipherData obj, System.Boolean alreadyEncrypted, System.Collections.Generic.Dictionary`2[TKey,TValue] localData) [0x0012b] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.Core.Services.CipherService+<>c__DisplayClass22_0.<GetAllAsync>b__0 (System.Collections.Generic.KeyValuePair`2[TKey,TValue] c) [0x00038] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToList () [0x0001b] in <89b8dc49ee2a4a61a8010ee9fc7c9a72>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <89b8dc49ee2a4a61a8010ee9fc7c9a72>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.Core.Services.CipherService.GetAllAsync () [0x0020c] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.Core.Services.CipherService.<GetAllDecryptedAsync>g__doTask|23_0 () [0x0014f] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.App.Pages.GroupingsPageViewModel.LoadDataAsync () [0x000bf] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.App.Pages.GroupingsPageViewModel.LoadAsync () [0x00416] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.App.Pages.GroupingsPage+<>c__DisplayClass15_0.<OnAppearing>b__1 () [0x001b4] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.App.Pages.BaseContentPage+<>c__DisplayClass11_0.<LoadOnAppearedAsync>g__DoWorkAsync|0 () [0x00071] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Bit.App.Pages.BaseContentPage+<>c__DisplayClass11_0.<LoadOnAppearedAsync>b__2 () [0x00068] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <8b5405f22643417f995402e834d2ceac>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.353  6061  6061 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)
11-08 22:07:20.354   808  3030 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
11-08 22:07:20.355   808  3030 I audio_hw_cirrus_playback: audio_extn_spkr_prot_stop_processing: pcm_tx_close
11-08 22:07:20.361  6061  6061 D AndroidRuntime: Shutting down VM
11-08 22:07:20.361  6061  6061 E AndroidRuntime: FATAL EXCEPTION: main
11-08 22:07:20.361  6061  6061 E AndroidRuntime: Process: com.x8bit.bitwarden, PID: 6061
11-08 22:07:20.361  6061  6061 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.Core.Models.Domain.Login..ctor (Bit.Core.Models.Data.LoginData obj, System.Boolean alreadyEncrypted) [0x00015] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.Core.Models.Domain.Cipher..ctor (Bit.Core.Models.Data.CipherData obj, System.Boolean alreadyEncrypted, System.Collections.Generic.Dictionary`2[TKey,TValue] localData) [0x0012b] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.Core.Services.CipherService+<>c__DisplayClass22_0.<GetAllAsync>b__0 (System.Collections.Generic.KeyValuePair`2[TKey,TValue] c) [0x00038] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToList () [0x0001b] in <89b8dc49ee2a4a61a8010ee9fc7c9a72>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <89b8dc49ee2a4a61a8010ee9fc7c9a72>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.Core.Services.CipherService.GetAllAsync () [0x0020c] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.Core.Services.CipherService.<GetAllDecryptedAsync>g__doTask|23_0 () [0x0014f] in <9f872fb189f94834a4003aff394890d6>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.App.Pages.GroupingsPageViewModel.LoadDataAsync () [0x000bf] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.App.Pages.GroupingsPageViewModel.LoadAsync () [0x00416] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.App.Pages.GroupingsPage+<>c__DisplayClass15_0.<OnAppearing>b__1 () [0x001b4] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.App.Pages.BaseContentPage+<>c__DisplayClass11_0.<LoadOnAppearedAsync>g__DoWorkAsync|0 () [0x00071] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Bit.App.Pages.BaseContentPage+<>c__DisplayClass11_0.<LoadOnAppearedAsync>b__2 () [0x00068] in <26e6ab0d79a14f20b188c6e5329517c2>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <8b5405f22643417f995402e834d2ceac>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <4ed8ad1e269942a1a95e75a1ad177714>:0
11-08 22:07:20.361  6061  6061 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-08 22:07:20.361  6061  6061 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-08 22:07:20.363   808  3030 D audio_hw_primary: disable_audio_route: usecase(25) reset and update mixer path: spkr-vi-record vi-feedback
11-08 22:07:20.363   808  3030 D audio_hw_primary: disable_snd_device: snd_device(104: vi-feedback)
11-08 22:07:20.366  1041  6230 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-08 22:07:20.367  1041  2380 W ActivityTaskManager:   Force finishing activity com.x8bit.bitwarden/.MainActivity
11-08 22:07:20.370  1041  3867 I AdrenoGLES: QUALCOMM build                   : ba734b1, I0a3e8c4129
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Build Date                       : 11/11/19
11-08 22:07:20.370  1041  3867 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Local Branch                     :
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.8.9.C1.08.00.00.516.287
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Remote Branch                    : NONE
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Reconstruct Branch               : NOTHING
11-08 22:07:20.370  1041  3867 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
11-08 22:07:20.374  1041  3867 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
11-08 22:07:20.377  1041  3867 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
11-08 22:07:20.378  1041  3867 I AdrenoGLES: PFP: 0x016ee183, ME: 0x00000000
11-08 22:07:20.378  1041  3867 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
11-08 22:07:20.395  1041  3867 E libc    : Access denied finding property "vendor.debug.egl.changepixelformat"
11-08 22:07:20.396  1041  3867 E BufferQueueProducer: [unnamed-1041-5] setMaxDequeuedBufferCount: 2 dequeued buffers would exceed the maxBufferCount (2) (maxAcquired 1 async 0 mDequeuedBufferCannotBlock 0)
11-08 22:07:20.396  1041  3867 E Surface : IGraphicBufferProducer::setBufferCount(3) returned Invalid argument
11-08 22:07:20.406  1041  3867 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
11-08 22:07:20.415  6061  6061 I Process : Sending signal. PID: 6061 SIG: 9
11-08 22:07:20.472  1041  1624 W InputDispatcher: channel '99dcd3 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-08 22:07:20.472  1041  1624 E InputDispatcher: channel '99dcd3 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-08 22:07:20.473  1041  2703 I ActivityManager: Process com.x8bit.bitwarden (pid 6061) has died: fore TOP
11-08 22:07:20.473  1041  1057 I WindowManager: WIN DEATH: Window{99dcd3 u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
11-08 22:07:20.473  1041  1057 W InputDispatcher: Attempted to unregister already unregistered input channel '99dcd3 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)'
11-08 22:07:20.474   795   795 I Zygote  : Process 6061 exited due to signal 9 (Killed)
11-08 22:07:20.498  1041  1294 W ActivityManager: setHasOverlayUi called on unknown pid: 6061
11-08 22:07:20.510  2772  2772 W Appboy v7.0.0 .j.c.a: SDK is disabled. Not performing action on SDK.
11-08 22:07:20.512  2922  3682 D GmsMeasureSvcImpl: f10: null
11-08 22:07:20.518  1041  1327 I libprocessgroup: Successfully killed process cgroup uid 10219 pid 6061 in 45ms
11-08 22:07:20.544  1785  1785 D ImageWallpaper: wallpaper visibility changes to: true
11-08 22:07:20.871  1041  1294 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f1ce8f3 u0 com.x8bit.bitwarden/.MainActivity t-1 f}
11-08 22:07:21.549  1041  1041 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
11-08 22:07:21.799  1041  2666 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
11-08 22:07:26.805   831   946 D CHRE    : @ 464.466: [ImuCal] Dynamic sensor configuration: stand-by.
11-08 22:07:26.956  2604  2624 I QcrilOemhookMsgTunnel: [0]processOemHookIndication length=21
11-08 22:07:26.957  2604  2604 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
11-08 22:07:27.048  2033  2033 D ServiceStateProvider: subId=1
11-08 22:07:27.055  1041  1057 D AlarmManagerService: Kernel timezone updated to -120 minutes west of GMT
```

**Comment by paulens12** [comment]
I tried building the tip of master in debug configuration and got the same error. Unfortunately, the debugger said "no compatible code is running" or something like that, so I couldn't pinpoint where the exception is coming from.

**Comment by paulens12** [comment]
Judging by the error, I had a guess that this has to do with the data on my server. I exported my vault to both json and csv formats and deleted everything. This time I could log in successfully.
I tried re-importing the json file - same error as before.
Interestingly enough, deleting everything again and importing the csv file solved the issue. I suspect there was some kind of special character somewhere that was escaped in csv, but I couldn't pinpoint it. It appears flaky, I tried splitting the json file in parts and the first part failed. Then I split that part into even smaller parts, and successfully restored all of them, without getting the error. So apparently sometimes restoring the same data causes this crash, and sometimes it doesn't.

It's also worth noting that none of my other clients (web, Windows, another Android device with the same build of Bitwarden) ever crashed. Seems like this device only started crashing because Bitwarden was freshly installed and had to download all the logins at once.

**Comment by tehniemer** [comment]
I have this same issue, however on a clean install of bitwarden with only one user and an empty vault.

**Comment by mportune-bw** [comment]
@paulens12 Thanks for the followup info.  Are you running the latest official server?

**Comment by paulens12** [comment]
actually I'm running bitwarden-rs. I'm not dismissing the possibility of something wrong being sent by the server, but the Firefox plugin and Windows client both work fine, even after logging out and back in. When I exported the passwords to csv, I found some entries with all fields blank except the name and skipped those when re-importing. Could that be an issue? I could see how that could cause a null reference exception in theory, and the other clients could just catch any errors and skip those entries.

**Comment by tehniemer** [comment]
@paulens12 My issue was an additional authentication layer in my reverse proxy settings. Do you have any sort of authentication in yours? If so, try disabling it.

**Comment by paulens12** [comment]
> @paulens12 My issue was an additional authentication layer in my reverse proxy settings. Do you have any sort of authentication in yours? If so, try disabling it.

nope, I don't have a reverse proxy

**Comment by cybiere** [comment]
Hi, same behaviour here, using bitwarden_rs aswell. Exporting in CSV, cleanup & re-importing seemed to work.

**Comment by ArneNaessens** [comment]
Hi, I'm also having the problem when i try to login into bitwarden the app just closes. Using fingerprint works tho.

**Comment by mportune-bw** [comment]
Just a reminder, as bitwarden_rs is not an official product, all issues (regardless of client) should be reported to them.

@ArneNaessens if you're using our cloud service or our official service, please open a new issue with any additional details you can provide.
