### ISSUE TITLE
Unable to login using reverse proxy

### ISSUE THREAD

**Issue by pittbull** [bitwarden/mobile#1304]
I have set up Bitwarden on docker located behind a nginx reverse proxy.

When accessing url in browser internally and externally, the login page shows correctly.

When accessing it from the Bitwarden app on my Iphone it works externally, but not internally. The following error message is given:

Exception message: The Internet connection appears to be offline.

This is logged under the api logged some of the times:

```
2021-03-09 15:08:22.054 +00:00 [Error] Unable to authenticate with identity server.
System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Bit.Core.Services.BaseIdentityClientService.HandleTokenStateAsync() in /home/runner/work/server/server/src/Core/Services/Implementations/BaseIdentityClientService.cs:line 108

```

Might anybody have any insights to this

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
