### ISSUE TITLE
can't launch app because missing "libmonodroid.so"

### ISSUE THREAD

**Issue by yopspanjers** [bitwarden/mobile#19]
On my Xiaomi mipad2 I can't open the app. On the error log it says it can't find libmonodroid.so. 

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.x8bit.bitwarden-2/base.apk"],nativeLibraryDirectories=[/data/app/com.x8bit.bitwarden-2/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libmonodroid.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:435)
	at java.lang.System.loadLibrary(System.java:988)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:34)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:22)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5018)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4613)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
	at android.app.ActivityThread.access$1500(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5275)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)`

**Comment by kspearrin** [comment]
Weird. What  version of android is the tablet running? Can you try uninstalling and reinstalling?

**Comment by yopspanjers** [comment]
Android 5.1 with the latest security patch (2016-11-01)

**Comment by yopspanjers** [comment]
I found a workaround by changing the supported architectures to just x86_64

**Comment by kspearrin** [comment]
@yopspanjers Where are you changing this architecture?

**Comment by yopspanjers** [comment]
Properties of the Android project > Android Options > Advanced

**Comment by kspearrin** [comment]
Interesting. I'll have to research this some more.

**Comment by kspearrin** [comment]
This should have been fixed since we added all architectures some time ago.
