### ISSUE TITLE
Crash when copy password to clipboard on my phone

### ISSUE THREAD

**Issue by zerofancy** [bitwarden/mobile#1962]
### Steps To Reproduce

1. Go to 'My Valut'
2. Click on any item, then you go 'View Item'
3. Click on copy password button.

### Expected Result

Password copied to clipboard

### Actual Result

Bitwarden crash.

```
06-22 10:16:55.072 24379 24379 D AndroidRuntime: Shutting down VM
06-22 10:16:55.072 24379 24379 E AndroidRuntime: FATAL EXCEPTION: main
06-22 10:16:55.072 24379 24379 E AndroidRuntime: Process: com.x8bit.bitwarden, PID: 24379
06-22 10:16:55.072 24379 24379 E AndroidRuntime: java.lang.SecurityException: Package com.ss.android.ugc.aweme does not belong to 10701
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2334)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:430)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:133)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:104)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.view.View.performClick(View.java:7750)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7727)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.view.View.access$3700(View.java:861)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29133)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8085)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at android.app.AppOpsManager.checkPackage(AppOpsManager.java:8739)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService.clipboardAccessAllowed(ClipboardService.java:989)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService.sendClipChangedBroadcast(ClipboardService.java:704)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternalLocked(ClipboardService.java:692)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 	at com.android.server.clipboard.ClipboardService.setPrimaryClipInternalLocked(ClipboardService.java:618)
06-22 10:16:55.072 24379 24379 E AndroidRuntime: 
```

[crash.log](https://github.com/bitwarden/mobile/files/8953956/crash.log)

### Operating System

Android

### Operating System Version

12

### Device

Redmi K40 Pro

### Build Version

2022.05.0（4636）

### Beta

- [ ] Using a pre-release version of the application.

**Comment by zerofancy** [comment]
I noticed that the text was copied to clipboard successfully. I think that just catch and ignore the RemoteException would work.

**Comment by yashwalter12** [comment]
@zerofancy  we are not able to reproduce the issue with the current steps on the latest version. Could you please check if this is still happening, If it is could you please give us little more information on it? Thank you

**Comment by zerofancy** [comment]
> @zerofancy we are not able to reproduce the issue with the current steps on the latest version. Could you please check if this is still happening, If it is could you please give us little more information on it? Thank you

**I can't reproduce the it either.** Maybe it has something to do with specific circumstances. My phone is:
Redmi K40 Pro
MIUI 13.0.6 (Android 12)
I installed the app from github release, and I also tried Google Play version at that time.
