### ISSUE TITLE
Android - Bitwarden crashes when attempting to generate a new password via the autofill flow.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/mobile#2143]
### Steps To Reproduce

1. Navigate to Vimeo.
2. Create a new Vimeo account.
3. Tap on the Email field.
4. Open Bitwarden via the Inline Autofill Service.
5. Tap on Add an item.
6. Attempt to generate a new password.

### Expected Result

To be able to generate a new password and save it.

### Actual Result

The Bitwarden application closes unexpectedly.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

Android

### Operating System Version

12.

### Device

Pixel 5.

### Build Version

2022.10.0.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sconim** [comment]
Same here. I've already reported the issue. I've noticed that if password get autogenerated as the very first action (before username and login name) the app doesn't crash. This might not be true on all entries. I've tested 2 entries.

**Comment by mjain234** [comment]
I have also faced same issue, the app crashes most of time when try to generate password during signing up in any websits or apps.

[Device Brand]: OPPO
[Device Model]: RMX1801
[Display]: RMX1801EX_11_F.12
[Android Version]: 10
[API Version]: 29
[System Locale]: en_GB
[Package Name]: com.x8bit.bitwarden
[Error Type]: Jvm
[Crash Time]: 2022-10-23T11:11:07.840
[Stack Trace]:
android.runtime.JavaProxyThrowable: System.InvalidOperationException: Access token not found.
  at Bit.Core.Services.TokenService.DecodeToken () [0x00017] in <6bbd8eb08de84d0da700c3afaf330468>:0 
  at Bit.Core.Services.TokenService.GetEmail () [0x00000] in <6bbd8eb08de84d0da700c3afaf330468>:0 
  at Bit.App.Pages.GeneratorPageViewModel.InitAsync () [0x00113] in <d2e72d1952de4a23ad908f6a1c2a6e04>:0 
  at Bit.App.Pages.GeneratorPage.InitAsync () [0x00067] in <d2e72d1952de4a23ad908f6a1c2a6e04>:0 
  at Bit.App.Pages.GeneratorPage.OnAppearing () [0x0007c] in <d2e72d1952de4a23ad908f6a1c2a6e04>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <54bfaac87bc54d4da3362feaa7fb8826>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <bfe604788d644a3381aa519955154abf>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <bfe604788d644a3381aa519955154abf>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <bfe604788d644a3381aa519955154abf>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <bfe604788d644a3381aa519955154abf>:0 
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7824)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
