### ISSUE TITLE
[2023.3.0/Android] Instant crash on startup: "Newtonsoft.Json.JsonReaderException: Could not convert string to integer: solarizeddark."

### ISSUE THREAD

**Issue by bentolor** [bitwarden/mobile#2429]
### Steps To Reproduce

1. Install version older than 2023.3.0
2. Set theme to solarized-dark
3. Upgrade to latest [2023.3.0] via F-Droid
4. Start. Instant Crash

### Expected Result

The application should appear.

### Actual Result

The application instantly crashes on startup

### Additional Context

I used MatLog Libre to get some logs and the following lines seem to reflect the culprit:

```
03-23 12:30:23.861 E/AndroidRuntime(27102): FATAL EXCEPTION: main
03-23 12:30:23.861 E/AndroidRuntime(27102): Process: com.x8bit.bitwarden, PID: 27102
03-23 12:30:23.861 E/AndroidRuntime(27102): android.runtime.JavaProxyThrowable: Newtonsoft.Json.JsonReaderException: Could not convert string to integer: solarizeddark. Path '', line 1, position 15.
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonReader.ReadInt32String (System.String s) [0x00062] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber (Newtonsoft.Json.ReadType readType) [0x00020] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonTextReader.ReadNumberValue (Newtonsoft.Json.ReadType readType) [0x0014a] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonTextReader.ReadAsInt32 () [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00051] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.LiteDbStorageService.GetAsync[T] (System.String key) [0x000fa] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateMigrationService.GetValueAsync[T] (Bit.Core.Services.StateMigrationService+Storage storage, System.String key) [0x00020] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateMigrationService.MigrateFrom3To4Async () [0x0061f] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateMigrationService.Migrate () [0x00208] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateService.CheckStateAsync () [0x00126] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateService.GetActiveUserIdAsync () [0x00077] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateService.GetDefaultStorageOptionsAsync () [0x00092] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Core.Services.StateService.GetLastBuildAsync () [0x00077] in <e6f242097c604b37bd9e069a38cff888>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.App.Utilities.AppHelpers.PerformUpdateTasksAsync (Bit.Core.Abstractions.ISyncService syncService, Bit.App.Abstractions.IDeviceActionService deviceActionService, Bit.Core.Abstractions.IStateService stateService) [0x000a4] in <d143e6a37f5e47aca60a17b31dee4632>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Bit.Droid.Receivers.PackageReplacedReceiver.OnReceive (Android.Content.Context context, Android.Content.Intent intent) [0x0007b] in <9791997d65ff4cf1b7631de71372bf4a>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <785761d8f68c4da68b16664a37357202>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102):   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
03-23 12:30:23.861 E/AndroidRuntime(27102): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at android.os.Handler.handleCallback(Handler.java:938)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at android.os.Looper.loop(Looper.java:223)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at java.lang.reflect.Method.invoke(Native Method)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-23 12:30:23.862 E/AndroidRuntime(27102): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Operating System

Android

### Operating System Version

lineage_oneplus3-userdebug 11 RQ3A.211001.001 a29a9ab544

### Device

OnePlus3T

### Build Version

2023.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SoiledBrush** [comment]
Same thing with black theme. Had to delete app data.

**Comment by cuzimhappyy** [comment]
same issue with nord theme. reinstalled app.

**Comment by D3SOX** [comment]
Got a similar crash log after upgrading to 2023.3.0 from the F-Droid repo
```
FATAL EXCEPTION: main
Process: com.x8bit.bitwarden, PID: 17472
android.runtime.JavaProxyThrowable: Newtonsoft.Json.JsonReaderException: Could not convert string to integer: black. Path '', line 1, position 7.
  at Newtonsoft.Json.JsonReader.ReadInt32String (System.String s) [0x00062] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber (Newtonsoft.Json.ReadType readType) [0x00020] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonTextReader.ReadNumberValue (Newtonsoft.Json.ReadType readType) [0x0014a] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonTextReader.ReadAsInt32 () [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00051] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <7ca8898b690a4181a32a9cf767cedb1e>:0 
  at Bit.Core.Services.LiteDbStorageService.GetAsync[T] (System.String key) [0x000fa] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateMigrationService.GetValueAsync[T] (Bit.Core.Services.StateMigrationService+Storage storage, System.String key) [0x00020] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateMigrationService.MigrateFrom3To4Async () [0x0051a] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateMigrationService.Migrate () [0x00208] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateService.CheckStateAsync () [0x00126] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateService.GetActiveUserIdAsync () [0x00077] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateService.GetDefaultStorageOptionsAsync () [0x00092] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.Core.Services.StateService.GetThemeAsync () [0x00077] in <e6f242097c604b37bd9e069a38cff888>:0 
  at Bit.App.Utilities.ThemeManager.GetTheme () [0x00019] in <d143e6a37f5e47aca60a17b31dee4632>:0 
  at Bit.App.Utilities.ThemeManager.SetTheme (Xamarin.Forms.ResourceDictionary resources) [0x00001] in <d143e6a37f5e47aca60a17b31dee4632>:0 
  at Bit.App.App.Bootstrap () [0x00019] in <d143e6a37f5e47aca60a17b31dee4632>:0 
  at Bit.App.App..ctor (Bit.App.Models.AppOptions appOptions) [0x000ec] in <d143e6a37f5e47aca60a17b31dee4632>:0 
  at Bit.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00168] in <9791997d65ff4cf1b7631de71372bf4a>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <accedc6f226b4ea8bf4fd67cc52a908b>:0 
	at com.x8bit.bitwarden.MainActivity.n_onCreate(Native Method)
	at com.x8bit.bitwarden.MainActivity.onCreate(MainActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:8305)
	at android.app.Activity.performCreate(Activity.java:8284)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by bentolor** [comment]
I assume with #2430 and 17b91e6fc46693eb364fd88b77a57fedc0802cbc a fix is already on the way.

**Comment by D3SOX** [comment]
Yeah, I've seen this PR. I hope it also works without deleting app data when upgrading to the upcoming version.

**Comment by mp-bw** [comment]
Apologies for the inconvenience everyone. `2023.3.1` will be released shortly, and it should work without having to clear any existing data.
