### ISSUE TITLE
Crash on android with 2 devices (android 9 armv7)

### ISSUE THREAD

**Issue by mathieuruellan** [bitwarden/mobile#2529]
### Steps To Reproduce

1- Enter login
2 - Enter password password

The app brutaly stops.

Tested on a moto g4 and a nexus  7 (lineageos 16/Android  9)

### Expected Result

Can see my vault

### Actual Result

App brutally stops

Log cat:
```
5-21 17:42:54.248 13782 13782 D AndroidRuntime: Shutting down VM
05-21 17:42:54.249 13782 13782 E AndroidRuntime: FATAL EXCEPTION: main
05-21 17:42:54.249 13782 13782 E AndroidRuntime: Process: com.x8bit.bitwarden, PID: 13782
05-21 17:42:54.249 13782 13782 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://vault.bitwarden.com/... }
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4545)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4906)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4874)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-21 17:42:54.249 13782 13782 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-21 17:42:54.276 13782 13782 I MonoDroid: UNHANDLED EXCEPTION:
05-21 17:42:54.282 13782 13782 I MonoDroid: Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://vault.bitwarden.com/... }
05-21 17:42:54.282 13782 13782 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <87e56e4d41da4c07bf8e84f086f08ecc>:0 
05-21 17:42:54.282 13782 13782 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00076] in <87e56e4d41da4c07bf8e84f086f08ecc>:0 
05-21 17:42:54.282 13782 13782 I MonoDroid:   at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <d9e08ee2a623400fae5cf496b4919bbb>:0 
05-21 17:42:54.282 13782 13782 I MonoDroid:   at Xamarin.Essentials.WebAuthenticator.PlatformAuthenticateAsync (Xamarin.Essentials.WebAuthenticatorOptions webAuthenticatorOptions) [0x00162] in <3ac133ebb0c24767aae3a685af5fe8f3>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Bit.App.Pages.LoginPageViewModel.LogInAsync (System.Boolean showLoading, System.Boolean checkForExistingAccount) [0x00636] in <848341a2bf61466c898c731611517141>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Bit.App.Pages.LoginPage.LogIn_Clicked (System.Object sender, System.EventArgs e) [0x00081] in <848341a2bf61466c898c731611517141>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <be9ebb417a95406cb70a92772d1a3790>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d9e08ee2a623400fae5cf496b4919bbb>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d9e08ee2a623400fae5cf496b4919bbb>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d9e08ee2a623400fae5cf496b4919bbb>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <d9e08ee2a623400fae5cf496b4919bbb>:0 
05-21 17:42:54.283 13782 13782 I MonoDroid:   --- End of managed Android.Content.ActivityNotFoundException stack trace ---
05-21 17:42:54.283 13782 13782 I MonoDroid: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://vault.bitwarden.com/... }
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Activity.startActivityForResult(Activity.java:4545)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Activity.startActivity(Activity.java:4906)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.Activity.startActivity(Activity.java:4874)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.os.Handler.handleCallback(Handler.java:873)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.os.Looper.loop(Looper.java:193)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-21 17:42:54.283 13782 13782 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-21 17:42:54.283 13782 13782 I MonoDroid: 
05-21 17:42:54.290   468  2608 W ActivityManager:   Force finishing activity com.x8bit.bitwarden/.MainActivity
05-21 17:42:54.309   468   484 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-21 17:42:54.309   468   484 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-21 17:42:54.316 13782 13782 I Process : Sending signal. PID: 13782 SIG: 9
05-21 17:42:54.377   468   481 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=79, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Unwanted:  Uid: 10092] ], android.os.BinderProxy@f159229)
05-21 17:42:54.378   468  2641 I WindowManager: WIN DEATH: Window{af32e7c u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
05-21 17:42:54.382   468   590 W InputDispatcher: channel '953cf60 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-21 17:42:54.382   468   590 E InputDispatcher: channel '953cf60 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-21 17:42:54.382   468  3628 I ActivityManager: Process com.x8bit.bitwarden (pid 13782) has died: vis  +99TOP 
05-21 17:42:54.382   468   487 W libprocessgroup: kill(-13782, 9) failed: No such process
05-21 17:42:54.389   468  8251 I WindowManager: WIN DEATH: Window{953cf60 u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
05-21 17:42:54.390   468  8251 W InputDispatcher: Attempted to unregister already unregistered input channel '953cf60 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity (server)'
05-21 17:42:54.395   213   213 I Zygote  : Process 13782 exited due to signal (9)
05-21 17:42:54.399   468   487 W libprocessgroup: kill(-13782, 9) failed: No such process
05-21 17:42:54.399   468   487 I libprocessgroup: Successfully killed process cgroup uid 10092 pid 13782 in 20ms
05-21 17:42:54.402   229  2420 W SurfaceFlinger: Attempting to set client state on removed layer: com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity#0
05-21 17:42:54.402   229  2420 W SurfaceFlinger: Attempting to destroy on removed layer: com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity#0
05-21 17:42:54.444   468  3629 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10034?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
05-21 17:42:54.462  2661  5921 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
05-21 17:42:54.463  2661  5921 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8960.so from current namespace instead of sphal namespace.
05-21 17:42:54.553   468   495 W ActivityManager: setHasOverlayUi called on unknown pid: 13782
05-21 17:42:54.556   229   369 W SurfaceFlinger: Attempting to set client state on removed layer: com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity#1
05-21 17:42:54.556   229   369 W SurfaceFlinger: Attempting to destroy on removed layer: com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity#1
05-21 17:42:54.561   229   364 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{b84658a token=Token{da363f5 ActivityRecord{cbcfd2c u0 com.x8bit.bitwarden/.MainActivity t22}}}#0
05-21 17:42:54.562   229   364 W SurfaceFlinger: Attempting to destroy on removed layer: Task=22#0
05-21 17:42:59.529   468   497 E LightsService: Light requested not available on this device. 2
```

### Operating System

Android

### Operating System Version

Lineage os  16/Android 9

### Device

nexus 7

### Build Version

com.x8bit.bitwarden.apk Version 2023.4.0 on github release page 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. It should work in your current OS version, but updating further if you are able, and then trying again may help.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
