### ISSUE TITLE
[Android]: App crashes when opening a package which is no longer installed

### ISSUE THREAD

**Issue by KobeW50** [bitwarden/mobile#3098]
### Steps To Reproduce

1. Go to an item in your vault that has a saved URI (aka package name) associated with that item.
2. Uninstall the app with that package name from your Android device.
3. Return to that item in the vault and press the "Open app" symbol near the URI for the uninstalled app.

### Expected Result

A toast or popup should appear saying that "App could not be found." Or "Cannot open URI." etc

### Actual Result

Bitwarden crashes. Here is the logs, when grepping for `AndroidRuntime`

```
FATAL EXCEPTION: main
Process: com.x8bit.bitwarden, PID: 330
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:618)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	... 1 more
Caused by: android.content.IntentSender$SendIntentException
	at android.content.IntentSender.sendIntent(IntentSender.java:245)
	at android.content.IntentSender.sendIntent(IntentSender.java:164)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
	at android.view.View.performClick(View.java:8043)
	at android.widget.TextView.performClick(TextView.java:17816)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:8020)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31850)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	... 3 more
```

### Screenshots or Videos

In this screen recording, I try opening the app with the package name `com.devhd.feedly`, but the app is not installed on my device. This causes Bitwarden to crash.

https://github.com/bitwarden/mobile/assets/84587632/258cae45-2603-4e74-a676-5c2be3525bdf

### Operating System

Android

### Operating System Version

Android 14

### Device

Samsung Galaxy S22+ (running One UI 6.0)

### Build Version

Version: 2024.3.0 (9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi @KobeW50 

I attempted to reproduce this issue on my Pixel device but was unable to do so. This could possibly be peculiar to your Samsung device. 

I will proceed to flag this to our engineering team.

Thank you for including screenshots or screen recordings,
