### ISSUE TITLE
first login crash at hyperos

### ISSUE THREAD

**Issue by rifaldi34** [bitwarden/mobile#3211]
### Steps To Reproduce

1. Login
2. Wait
3. Crash

### Expected Result

can login and use app

### Actual Result

crashes

### Additional Context

android.content.ActivityNotFoundException:

No Activity found to handle Intent

{act=android.intent.action.VIEW

dat=https://vault.bitwarden.com/...}

at

android.app.Instrumentation.checkStartActivity Result(Unknown Source:137)

at

android.app.Instrumentation.execStartActivity(U nknown Source:212)

at

android.app.Activity.startActivityForResult(Unkn own Source:34)

at

androidx.activity.ComponentActivity.startActivity ForResult(ComponentActivity.java:754)

at

android.app.Activity.startActivityForResult(Unkn own Source:1)

at

androidx.activity.ComponentActivity.startActivity ForResult(ComponentActivity.java:735) at android.app.Activity.startActivity(Unknown Source:16)

at android.app.Activity.startActivity(Unknown Source:1)

at

mono.java.lang.Runnablelmplementor.n_run(Nati ve Method)

at

mono.java.lang.Runnablelmplementor.run(Runna blelmplementor.java:31)

at android.os.Handler.handleCallback(Unknown Source:2)

at android.os.Handler.dispatchMessage(Unknown Source:4)

at android.os.Looper.loop Once(Unknown

Source:182)

at android.os.Looper.loop(Unknown Source:82)

at android.app.ActivityThread.main(Unknown Source:123)

at java.lang.reflect.Method.invoke(Native

Method)

at

com.android.internal.os.RuntimeInit$MethodAn dArgsCaller.run(Unknown Source:11)

at

com.android.internal.os.ZygoteInit.main(Unknow n Source:312)

### Operating System

Android

### Operating System Version

13

### Device

redmi note 12 pro 4g

### Build Version

2024.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by rifaldi34** [comment]
Found fix -_- its because the default browser is not detected and bitwarden wanted to ask captcha

fix solution : install chrome / firefox
