### ISSUE TITLE
App crashes when logging in

### ISSUE THREAD

**Issue by KevinSchildhorn** [bitwarden/mobile#3386]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Open Bitwarden app
2. Enter master password
3. Click on 'Unlock'

crash

### Expected Result

I can see all of my passwords

### Actual Result

The app crashes

### Additional Context

```FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.x8bit.bitwarden, PID: 9724
                                                                                                    android.runtime.JavaProxyThrowable: [Bit.Core.Models.Domain.SymmetricCryptoKey+ArgumentKeyNullException]: ArgumentNull_Generic Arg_ParamName_Name, key
                                                                                                    	at Bit.Core.Models.Domain.SymmetricCryptoKey..ctor(Unknown Source:0)
                                                                                                    	at Bit.Core.Models.Domain.CipherKey..ctor(Unknown Source:0)
                                                                                                    	at Bit.Core.Models.Domain.Cipher+<DecryptAsync>d__98.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter`1[[Bit.Core.Models.View.CipherView, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetResult(Unknown Source:0)
                                                                                                    	at Bit.Core.Services.CipherService+<>c__DisplayClass28_1+<<GetAllDecryptedAsync>g__decryptAndAddCipherAsync|1>d.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at Bit.Core.Services.CipherService+<>c__DisplayClass28_0+<<GetAllDecryptedAsync>g__doTask|0>d.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Collections.Generic.List`1[[Bit.Core.Models.View.CipherView, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult(Unknown Source:0)
                                                                                                    	at Bit.Core.Services.CipherService+<GetAllDecryptedAsync>d__28.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Collections.Generic.List`1[[Bit.Core.Models.View.CipherView, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.VaultFilterViewModel+<GetAllCiphersAsync>d__29.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Collections.Generic.List`1[[Bit.Core.Models.View.CipherView, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.GroupingsPageViewModel+<LoadDataAsync>d__171.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.GroupingsPageViewModel+<LoadAsync>d__156.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.GroupingsPageViewModel+<LoadAsync>d__156.MoveNext(Unknown Source:0)
2024-09-07 10:04:23.261  9724-9724  AndroidRuntime          com.x8bit.bitwarden                  E  	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0) (Ask Gemini)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.GroupingsPage+<<OnAppearing>b__13_1>d.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.BaseContentPage+<>c__DisplayClass23_0+<<LoadOnAppearedAsync>g__DoWorkAsync|0>d.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
                                                                                                    	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
                                                                                                    	at Bit.App.Pages.BaseContentPage+<>c__DisplayClass23_0+<<LoadOnAppearedAsync>b__2>d.MoveNext(Unknown Source:0)
                                                                                                    	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
                                                                                                    	at System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(Unknown Source:0)
                                                                                                    	at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0(Unknown Source:0)
                                                                                                    	at Java.Lang.Thread+RunnableImplementor.Run(Unknown Source:0)
                                                                                                    	at Java.Lang.IRunnableInvoker.n_Run(Unknown Source:0)
                                                                                                    	at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
                                                                                                    	at mono.java.lang.RunnableImplementor.n_run(Native Method)
                                                                                                    	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)```

### Operating System

Android

### Operating System Version

_No response_

### Device

Google Pixel 7

### Build Version

2024.7.1

**Comment by SergeantConfused** [comment]
Hello @KevinSchildhorn,

Thank you for reporting this. I recommend proceeding with a fresh new installation; Please uninstall Bitwarden off your Android device, turn your device off (long press) and back on, install Bitwarden anew from the Google Play Store, and test that once more; Please remember to activate all the supported Auto-Fill services as outlined here (https://bitwarden.com/help/auto-fill-android/). I say this because I am unable to reproduce this in testing.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
