### ISSUE TITLE
Android app 2.3.1 crash

### ISSUE THREAD

**Issue by mholecy** [bitwarden/mobile#833]
## App crash
After update to the latest beta (2.3.1) when I open app it instantly crash. 

## Steps To Reproduce

1. Install app with version 2.3.1
2. Open app

## Environment

- Device: Nokia 7 plus (TA-1046)
- Operating system: Android 10
- Build Version: 2.3.1
- Is this a Beta release? Yes

## Stacktrace
```
2020-04-15 11:08:36.005 28577-28577/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.x8bit.bitwarden, PID: 28577
    android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'LiteDB.BsonExpression' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
    Parameter name: method
      at System.Linq.Expressions.Expression.Call (System.Reflection.MethodInfo method, System.Linq.Expressions.Expression arg0, System.Linq.Expressions.Expression arg1) [0x00068] in <b0037b07c89b44f9bf29887da14b4658>:0 
      at LiteDB.BsonExpressionParser.TryParsePath (LiteDB.Tokenizer tokenizer, LiteDB.ExpressionContext context, System.Boolean isRoot) [0x000de] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.BsonExpressionParser.ParseSingleExpression (LiteDB.Tokenizer tokenizer, LiteDB.ExpressionContext context, System.Boolean isRoot) [0x00094] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.BsonExpressionParser.ParseFullExpression (LiteDB.Tokenizer tokenizer, LiteDB.ExpressionContext context, System.Boolean isRoot) [0x00000] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.BsonExpression.Parse (LiteDB.Tokenizer tokenizer, LiteDB.BsonExpressionParserMode mode, System.Boolean isRoot) [0x00054] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.BsonExpression.Create (System.String expression) [0x00028] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.BsonExpression..cctor () [0x0000a] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
       --- End of inner exception stack trace ---
      at LiteDB.Engine.LiteEngine.RebuildContent (LiteDB.Engine.IFileReader reader) [0x00118] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.Engine.LiteEngine.Upgrade (System.String filename, System.String password) [0x00106] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.LiteDatabase..ctor (LiteDB.ConnectionString connectionString, LiteDB.BsonMapper mapper) [0x00028] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.LiteDatabase..ctor (System.String connectionString, LiteDB.BsonMapper mapper) [0x00007] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at Bit.Core.Services.LiteDbStorageService.<InitAsync>b__5_0 () [0x00015] in <c357100c811f48f099f33746186395a1>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1caf55231bdd4bb483764b9b31b31ebe>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in <1caf55231bdd4bb483764b9b31b31ebe>:0 
    --- End of stack trace from previous location where exception was thrown ---
    
      at Bit.Core.Services.LiteDbStorageService.GetAsync[T] (System.String key) [0x00084] in <c357100c811f48f099f33746186395a1>:0 
      at Bit.App.Services.MobileStorageService.GetAsync[T] (System.String key) [0x0013b] in <ab8465693fdb481aa44e5dbe887eb411>:0 
      at Bit.Core.Services.TokenService.GetTokenAsync () [0x00083] in <c357100c811f48f099f33746186395a1>:0 
      at Bit.Core.Services.UserService.IsAuthenticatedAsync () [0x00071] in <c357100c811f48f099f33746186395a1>:0 
      at LiteDB.Engine.LiteEngine.RebuildContent (LiteDB.Engine.IFileReader reader) [0x00118] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.Engine.LiteEngine.Upgrade (System.String filename, System.String password) [0x00106] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.LiteDatabase..ctor (LiteDB.ConnectionString connectionString, LiteDB.BsonMapper mapper) [0x00028] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at LiteDB.LiteDatabase..ctor (System.String connectionString, LiteDB.BsonMapper mapper) [0x00007] in <da3b55f2020d4ca38f320e2cd4b6423d>:0 
      at Bit.Core.Services.LiteDbStorageService.<InitAsync>b__5_0 () [0x00015] in <c357100c811f48f099f33746186395a1>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1caf55231bdd4bb483764b9b31b31ebe>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in <1caf55231bdd4bb483764b9b31b31ebe>:0 
    --- End of stack trace from previous location where exception was thrown ---
    
      at Bit.Core.Services.LiteDbStorageService.GetAsync[T] (System.String key) [0x00084] in <c357100c811f48f099f33746186395a1>:0 
2020-04-15 11:08:36.005 28577-28577/? E/AndroidRuntime:   at Bit.App.Services.MobileStorageService.GetAsync[T] (System.String key) [0x0013b] in <ab8465693fdb481aa44e5dbe887eb411>:0 
      at Bit.Core.Services.TokenService.GetTokenAsync () [0x00083] in <c357100c811f48f099f33746186395a1>:0 
      at Bit.Core.Services.UserService.IsAuthenticatedAsync () [0x00071] in <c357100c811f48f099f33746186395a1>:0 
      at Bit.Core.Services.EventService.UploadEventsAsync () [0x00080] in <c357100c811f48f099f33746186395a1>:0 
      at Bit.Droid.Receivers.EventUploadReceiver.OnReceive (Android.Content.Context context, Android.Content.Intent intent) [0x00065] in <a6c82668eb8f4c5198b6b5c7270873fe>:0 
      at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <1caf55231bdd4bb483764b9b31b31ebe>:0 
      at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <2d0de8a221e34f1eb8819be4a9e3a57b>:0 
      at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2d0de8a221e34f1eb8819be4a9e3a57b>:0 
      at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <2d0de8a221e34f1eb8819be4a9e3a57b>:0 
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.28(intptr,intptr)
        at mono.java.lang.RunnableImplementor.n_run(Native Method)
        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

**Comment by tgreer-bw** [comment]
@mholecy - the current beta build crashes, unfortunately. We have a fix, but it hasn't been approved for the play store yet. You can find a link to a fixed build and more backstory here: https://https://github.com/bitwarden/mobile/issues/805
